# Site settings
title: MINLMINL88's Blog
email: tyoon88.ty@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/minlminl88/" # the subpath of your site, e.g. /blog/
url: "http://minlminl88.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  minlminl88

# Build settings
markdown: kramdown
