# Site settings
title: MINLMINL88's Blog
email: tyoon88.ty@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  IMI is a creative design agency. We help organizations use design for their best and make better decisions.
baseurl: "/minlminl88/" # the subpath of your site, e.g. /blog/
url: "http://minlminl88.github.io" # the base hostname & protocol for your site
twitter_username: LietuTy
github_username:  minlminl88
skype_username: tyoon88.ty

# Build settings
markdown: kramdown
